// components/Headshots.vue
<template>
  <div class="headshots">
    <div ref="headshot" :class="headshot" class="headshots__image">
      <picture>
        <source
          :srcset="previewAvif"
          :data-srcset="srcsetAvif"
          :sizes="sizes"
          type="image/avif"
        />
        <source
          :srcset="previewWebp"
          :data-srcset="srcsetWebp"
          :sizes="sizes"
          type="image/webp"
        />
        <source :data-srcset="srcset" :sizes="sizes" type="image/png" />
        <img
          :src="preview"
          :class="{ 'lazy__image--load': mounted }"
          alt="Interactive photo of Greg Ives"
          class="lazy__image"
          width="3150"
          height="2400"
        />
      </picture>
    </div>
  </div>
</template>

<script>
import headshots from '~/config/headshots'

export default {
  data() {
    return {
      closestHeadshot: 'fd',
      mounted: false,
      x: null,
      y: null,
      rAF: null,
      sizes: '(min-width: 1200px) 25vw, (min-width: 992px) 33vw, 50vw'
    }
  },
  computed: {
    headshot() {
      return `headshots__image--${this.closestHeadshot}`
    },
    preview() {
      return require('~/assets/images/headshots--fd.png')
    },
    previewWebp() {
      return require('~/assets/images/headshots--fd.png?format=webp')
    },
    previewAvif() {
      return require('~/assets/images/headshots--fd.png?format=avif')
    },
    srcset() {
      return require(`~/assets/images/headshots.png`)
    },
    srcsetWebp() {
      return require(`~/assets/images/headshots.png?format=webp`)
    },
    srcsetAvif() {
      return require(`~/assets/images/headshots.png?format=avif`)
    }
  },
  mounted() {
    this.mounted = true

    window.addEventListener('mousemove', this.storeMousePosition)
    window.addEventListener('touchstart', this.storeMousePosition)
    window.addEventListener('touchmove', this.storeMousePosition)

    this.rAF = requestAnimationFrame(this.changeHeadshot)
  },
  beforeDestroy() {
    window.removeEventListener('mousemove', this.storeMousePosition)
    window.removeEventListener('touchstart', this.storeMousePosition)
    window.removeEventListener('touchmove', this.storeMousePosition)

    cancelAnimationFrame(this.rAF)
  },
  methods: {
    storeMousePosition(event) {
      try {
        this.x = event.clientX || event.changedTouches[0].clientX
        this.y = event.clientY || event.changedTouches[0].clientY
      } catch {
        // Don't worry about errors
      }
    },
    changeHeadshot() {
      if (this.x === null || this.y === null) {
        this.rAF = requestAnimationFrame(this.changeHeadshot)
        return
      }

      let rect
      try {
        rect = this.$refs.headshot.getBoundingClientRect()
      } catch (error) {
        this.rAF = requestAnimationFrame(this.changeHeadshot)
        return
      }

      const mouseX = ((this.x - rect.left) * 10) / rect.width
      const mouseY = ((this.y - rect.top) * 10) / rect.height

      const closestHeadshot = headshots.reduce(
        (closest, headshot) => {
          const pointX = headshot[0]
          const pointY = headshot[1]

          const distance = {
            x: Math.abs(mouseX - pointX),
            y: Math.abs(mouseY - pointY)
          }

          const equalY = distance.y === closest.distance.y
          const closerY = distance.y < closest.distance.y
          const closerX = distance.x < closest.distance.x

          return closerY || (equalY && closerX)
            ? { distance, headshot }
            : closest
        },
        {
          distance: {
            x: Infinity,
            y: Infinity
          },
          headshot: headshots[0]
        }
      ).headshot

      this.closestHeadshot = [
        closestHeadshot[0] < 0 ? '_' : '',
        String.fromCharCode(97 + Math.abs(closestHeadshot[0])),
        closestHeadshot[1] < 0 ? '_' : '',
        String.fromCharCode(97 + Math.abs(closestHeadshot[1]))
      ].join('')

      this.rAF = requestAnimationFrame(this.changeHeadshot)
    }
  }
}
</script>

<style lang="scss">
.headshots {
  filter: sepia(1) hue-rotate(-35deg) hue-rotate($color__primary--hue)
    saturate(2) brightness(1.1);
  height: calc(12rem + 20vh - 0.5rem);
  margin: 0 auto;
  overflow: hidden;
  position: relative;
  width: calc(9rem + 15vh); // Aspect ratio of 4:3
}

.headshots__image {
  bottom: -0.5rem;
  height: calc(100% + 1rem);
  right: 0;
  position: absolute;
  width: 100%;

  .lazy__image {
    display: block;
    filter: none;
    height: auto;
    left: 0;
    margin: 0;
    max-width: none;
    position: absolute;
    top: 0;
    transform: translate(math.div(-400%, 7), math.div(-300%, 4));
    width: 700%;
  }
}

.headshots__image--_k_f .lazy__image--loaded {
  transform: translate(0, 0);
}

.headshots__image--_la .lazy__image--loaded {
  transform: translate(math.div(-100%, 7), 0);
}

.headshots__image--_pd .lazy__image--loaded {
  transform: translate(math.div(-200%, 7), 0);
}

.headshots__image--_r_f .lazy__image--loaded {
  transform: translate(math.div(-300%, 7), 0);
}

.headshots__image--_sa .lazy__image--loaded {
  transform: translate(math.div(-400%, 7), 0);
}

.headshots__image--_bd .lazy__image--loaded {
  transform: translate(math.div(-500%, 7), 0);
}

.headshots__image--ia .lazy__image--loaded {
  transform: translate(math.div(-600%, 7), 0);
}

.headshots__image--_ug .lazy__image--loaded {
  transform: translate(0, math.div(-100%, 4));
}

.headshots__image--_xd .lazy__image--loaded {
  transform: translate(math.div(-100%, 7), math.div(-100%, 4));
}

.headshots__image--_c_f .lazy__image--loaded {
  transform: translate(math.div(-200%, 7), math.div(-100%, 4));
}

.headshots__image--_da .lazy__image--loaded {
  transform: translate(math.div(-300%, 7), math.div(-100%, 4));
}

.headshots__image--_f_f .lazy__image--loaded {
  transform: translate(math.div(-400%, 7), math.div(-100%, 4));
}

.headshots__image--_hg .lazy__image--loaded {
  transform: translate(math.div(-500%, 7), math.div(-100%, 4));
}

.headshots__image--id .lazy__image--loaded {
  transform: translate(math.div(-600%, 7), math.div(-100%, 4));
}

.headshots__image--_jd .lazy__image--loaded {
  transform: translate(0, math.div(-200%, 4));
}

.headshots__image--ag .lazy__image--loaded {
  transform: translate(math.div(-100%, 7), math.div(-200%, 4));
}

.headshots__image--k_f .lazy__image--loaded {
  transform: translate(math.div(-200%, 7), math.div(-200%, 4));
}

.headshots__image--ma .lazy__image--loaded {
  transform: translate(math.div(-300%, 7), math.div(-200%, 4));
}

.headshots__image--od .lazy__image--loaded {
  transform: translate(math.div(-400%, 7), math.div(-200%, 4));
}

.headshots__image--og .lazy__image--loaded {
  transform: translate(math.div(-500%, 7), math.div(-200%, 4));
}

.headshots__image--jg .lazy__image--loaded {
  transform: translate(math.div(-600%, 7), math.div(-200%, 4));
}

.headshots__image--c_f .lazy__image--loaded {
  transform: translate(0, math.div(-300%, 4));
}

.headshots__image--ca .lazy__image--loaded {
  transform: translate(math.div(-100%, 7), math.div(-300%, 4));
}

.headshots__image--ea .lazy__image--loaded {
  transform: translate(math.div(-200%, 7), math.div(-300%, 4));
}

.headshots__image--f_f .lazy__image--loaded {
  transform: translate(math.div(-300%, 7), math.div(-300%, 4));
}

.headshots__image--fd .lazy__image--loaded {
  transform: translate(math.div(-400%, 7), math.div(-300%, 4));
}

.headshots__image--fg .lazy__image--loaded {
  transform: translate(math.div(-500%, 7), math.div(-300%, 4));
}
</style>

// components/Headshots.tsx
"use client";

import Image from "next/image";
import fullImage from "@/assets/headshots.png";
import previewImage from "@/assets/headshotsPreview.png";
import { useCallback, useEffect, useRef, useState } from "react";

type HeadshotsProperties = JSX.IntrinsicElements["div"];

type Headshot = {
  coordinates: [number, number];
  transform: string;
};

export function Headshots(properties: HeadshotsProperties) {
  const [loaded, setLoaded] = useState(false);
  const [transform, setTransform] = useState(
    `translate(-${400 / 7}%, -${300 / 4}%)`
  );

  const headshotsRef = useRef<HTMLDivElement>(null);

  const changeHeadshot = useCallback((event: MouseEvent | TouchEvent) => {
    if (headshotsRef.current === null) {
      return;
    }

    const [clientX, clientY] = [
      "clientX" in event ? event.clientX : event.changedTouches[0].clientX,
      "clientY" in event ? event.clientY : event.changedTouches[0].clientY,
    ];

    const rect = headshotsRef.current.getBoundingClientRect();
    const mouseX = ((clientX - rect.left) * 10) / rect.width;
    const mouseY = ((clientY - rect.top) * 10) / rect.height;

    const { headshot: closestHeadshot } = headshots.reduce(
      (closest, headshot) => {
        const [headshotX, headshotY] = headshot.coordinates;

        const distance = {
          x: Math.abs(mouseX - headshotX),
          y: Math.abs(mouseY - headshotY),
        };

        const equalY = distance.y === closest.distance.y;
        const closerY = distance.y < closest.distance.y;
        const closerX = distance.x < closest.distance.x;

        return closerY || (equalY && closerX)
          ? { distance, headshot }
          : closest;
      },
      {
        distance: {
          x: Infinity,
          y: Infinity,
        },
        headshot: headshots[0],
      }
    );

    setTransform(closestHeadshot.transform);
  }, []);

  useEffect(() => {
    if (loaded) {
      window.addEventListener("mousemove", changeHeadshot);
      window.addEventListener("touchstart", changeHeadshot);
      window.addEventListener("touchmove", changeHeadshot);
    }

    return () => {
      window.removeEventListener("mousemove", changeHeadshot);
      window.removeEventListener("touchstart", changeHeadshot);
      window.removeEventListener("touchmove", changeHeadshot);
    };
  }, [loaded, changeHeadshot]);

  return (
    <div {...properties}>
      <div className="mx-auto max-w-[50vw] -mb-8">
        <div className="overflow-hidden">
          <div
            className="relative w-full pb-[133.3333%] -m-1"
            ref={headshotsRef}
          >
            {!loaded && (
              <Image
                src={previewImage}
                alt="Photo of Greg Ives"
                className="absolute top-0 left-0 w-[700%] max-w-none mix-blend-hard-light dark:contrast-0 dark:mix-blend-luminosity"
                style={{
                  transform,
                }}
                priority
                sizes="(min-width: 768px) 233.3333vw, 350vw"
              />
            )}
            <Image
              src={fullImage}
              alt="Photo of Greg Ives"
              className="absolute top-0 left-0 w-[700%] max-w-none mix-blend-hard-light dark:contrast-0 dark:mix-blend-luminosity"
              style={{
                transform,
                visibility: loaded ? "visible" : "hidden",
              }}
              onLoad={() => setLoaded(true)}
              sizes="(min-width: 768px) 233.3333vw, 350vw"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

const headshots: Headshot[] = [
  {
    coordinates: [-10, -5],
    transform: `translate(0, 0)`,
  },
  {
    coordinates: [-11, 0],
    transform: `translate(-${100 / 7}%, 0)`,
  },
  {
    coordinates: [-15, 3],
    transform: `translate(-${200 / 7}%, 0)`,
  },
  {
    coordinates: [-17, -5],
    transform: `translate(-${300 / 7}%, 0)`,
  },
  {
    coordinates: [-18, 0],
    transform: `translate(-${400 / 7}%, 0)`,
  },
  {
    coordinates: [-1, 3],
    transform: `translate(-${500 / 7}%, 0)`,
  },
  {
    coordinates: [-20, 6],
    transform: `translate(0, -${100 / 4}%)`,
  },
  {
    coordinates: [-23, 3],
    transform: `translate(-${100 / 7}%, -${100 / 4}%)`,
  },
  {
    coordinates: [-2, -5],
    transform: `translate(-${200 / 7}%, -${100 / 4}%)`,
  },
  {
    coordinates: [-3, 0],
    transform: `translate(-${300 / 7}%, -${100 / 4}%)`,
  },
  {
    coordinates: [-5, -5],
    transform: `translate(-${400 / 7}%, -${100 / 4}%)`,
  },
  {
    coordinates: [-7, 6],
    transform: `translate(-${500 / 7}%, -${100 / 4}%)`,
  },
  {
    coordinates: [-9, 3],
    transform: `translate(0, -${200 / 4}%)`,
  },
  {
    coordinates: [0, 6],
    transform: `translate(-${100 / 7}%, -${200 / 4}%)`,
  },
  {
    coordinates: [10, -5],
    transform: `translate(-${200 / 7}%, -${200 / 4}%)`,
  },
  {
    coordinates: [12, 0],
    transform: `translate(-${300 / 7}%, -${200 / 4}%)`,
  },
  {
    coordinates: [14, 3],
    transform: `translate(-${400 / 7}%, -${200 / 4}%)`,
  },
  {
    coordinates: [14, 6],
    transform: `translate(-${500 / 7}%, -${200 / 4}%)`,
  },
  {
    coordinates: [2, -5],
    transform: `translate(0, -${300 / 4}%)`,
  },
  {
    coordinates: [2, 0],
    transform: `translate(-${100 / 7}%, -${300 / 4}%)`,
  },
  {
    coordinates: [4, 0],
    transform: `translate(-${200 / 7}%, -${300 / 4}%)`,
  },
  {
    transform: `translate(-${300 / 7}%, -${300 / 4}%)`,
    coordinates: [5, -5],
  },
  {
    transform: `translate(-${400 / 7}%, -${300 / 4}%)`,
    coordinates: [5, 3],
  },
  {
    transform: `translate(-${500 / 7}%, -${300 / 4}%)`,
    coordinates: [5, 6],
  },
  {
    coordinates: [8, 0],
    transform: `translate(-${600 / 7}%, 0)`,
  },
  {
    coordinates: [8, 3],
    transform: `translate(-${600 / 7}%, -${100 / 4}%)`,
  },
  {
    coordinates: [9, 6],
    transform: `translate(-${600 / 7}%, -${200 / 4}%)`,
  },
];
